
export const templates = [
  {
    id: 1,
    name: "Dark Navbar with Search",
    style: {
      backgroundColor: "#1A1F2C",
      textColor: "#ffffff",
      activeColor: "#9b87f5",
      hoverColor: "#7E69AB",
      borderRadius: "0px",
      hasSearch: true,
      navPosition: "left",
      height: "64px",
      padding: "0 24px",
      borderWidth: "0px",
      borderColor: "#1A1F2C",
      searchBarBackgroundColor: "rgba(255, 255, 255, 0.1)",
      searchPlaceholderColor: "#cccccc",
      searchIconColor: "#cccccc",
      SearchBorderWidth: "1px",
      SearchBarBorderColor: "rgba(255, 255, 255, 0.2)",
      searchBorderRadius: "6px",
      icons: {
        notification: { show: true, variant: "bell", color: "#ffffff" },
        profile: { show: true, variant: "user", color: "#ffffff" },
      },
    },
    navItems: [
      { id: 1, text: "Home", active: true, url: "/" },
      { id: 2, text: "About", active: false, url: "/About" },
      { id: 3, text: "Contact", active: false, url: "/Contact" },
    ],
  },
  {
    id: 2,
    name: "Light Rounded Navbar",
    style: {
      backgroundColor: "#ffffff",
      textColor: "#333333",
      activeColor: "#9b87f5",
      hoverColor: "#7E69AB",
      borderRadius: "8px",
      hasSearch: true,
      navPosition: "right",
      height: "64px",
      padding: "0 24px",
      borderWidth: "1px",
      borderColor: "#e5e7eb",
      searchBarBackgroundColor: "#f9fafb",
      searchPlaceholderColor: "#6b7280",
      searchIconColor: "#6b7280",
      SearchBorderWidth: "1px",
      SearchBarBorderColor: "#e5e7eb",
      searchBorderRadius: "6px",
      icons: {
        notification: { show: true, variant: "bell", color: "#333333" },
        profile: { show: true, variant: "user", color: "#333333" },
      },
    },
    navItems: [
      { id: 1, text: "Home", active: true, url: "/" },
      { id: 2, text: "About", active: false, url: "/About" },
      { id: 3, text: "Contact", active: false, url: "/Contact" },
    ],
  },
];
